class UsersController < ApplicationController
  # if the auto_login route is accessed in application, the authorized method in application controller runs first
  before_action :authorized, only: [:auto_login]

  # REGISTER
  def create
    @user = User.create(user_params)
    if @user.valid?
      # encode_token will return a token string generated by JWT. A JSON object is rendered with the key-value pairs of the user and token as a response.
      token = encode_token({user_id: @user.id})
      render json: {user: @user, token: token}
    else
      render json: {error: "Invalid username or password"}
    end
  end

  # LOGGING IN
  def login
    @user = User.find_by(username: params[:username])

    # the authenticate method provided by bcrypt compares if the password passed from the params and the password stored in the database match
    if @user && @user.authenticate(params[:password])
      # encode_token will return a token string generated by JWT. A JSON object is rendered with the key-value pairs of the user and token as a response.
      token = encode_token({user_id: @user.id})
      render json: {user: @user, token: token}
    else
      render json: {error: "Invalid username or password"}
    end
  end


  def auto_login
    # Since the method, authorized, will run before auto_login, the chain of methods in the application controller will also run
    # One of the methods, logged_in_user, will return a global @user variable that is accessible.
    render json: @user
  end

  private

  def user_params
    params.permit(:username, :password)
  end
end
